fix: add ftFidSelection options
cheminfo/brukerconverter pull request #90
Opened 2023-02-16 10:53 UTC by jobo322

with it is it possible to priorize one over the other FT/FID

2023-02-16 11:02 UTC, lpatiny commented
After discussion with @targos it would make more sense to remove the properties 'keepFID' and 'keepFT' in favour of:

- dataSelection: 'fid' | 'ft' | 'both' | 'preferFT' | 'preferFID'

2023-02-17 14:14 UTC, lpatiny requested changes
If this is a draft please take the habit to `gh pr create --fill --draft`

2023-02-17 14:14 UTC, lpatiny commented on package.json
> +    "node": "18.14.0"
Why are you forcing volta version ? This should not be there I think.

2023-02-17 14:14 UTC, lpatiny commented on src/groupByExperiments.js
> +    console.log('pasa')
Console.log should disappar and the '.only' on the testcase as well.

2023-02-17 14:43 UTC, jobo322 commented on package.json
> +    "node": "18.14.0"
my mistake, sorry

2023-02-17 17:18 UTC, lpatiny commented on brukerconverter.d.ts
>     * priories processed or raw data if both exists
Comment does not seem correct

2023-02-21 14:30 UTC, merged